import { inngest } from "@/lib/inngest/client.ts";
import {
  aiInfer,
  aiInferMultiStep,
  anthropicWrapMessageCreate,
  conditionalConcurrency,
  fetchOtel,
  genericWrapGenerateText,
  happyPath,
  helloWorld,
  input,
  longRunning,
  manySteps,
  multipleErrors,
  nonRetriable,
  openAIWrapCompletionCreate,
  parallelWaitForEvent,
  sendEvent,
  sequentialWaitForEvent,
  specialCharacters,
  stepInvoke,
  stepless,
  stepRunFetchOpenAI,
  throwError,
  vercelWrapGenerateText,
} from "@/lib/inngest/functions.ts";
import { serve } from "inngest/deno/fresh";

export const handler = serve({
  client: inngest,
  functions: [
    helloWorld,
    genericWrapGenerateText,
    anthropicWrapMessageCreate,
    openAIWrapCompletionCreate,
    vercelWrapGenerateText,
    aiInfer,
    aiInferMultiStep,
    fetchOtel,
    stepRunFetchOpenAI,
    stepInvoke,
    longRunning,
    nonRetriable,
    manySteps,
    multipleErrors,
    stepless,
    input,
    sendEvent,
    throwError,
    conditionalConcurrency,
    parallelWaitForEvent,
    sequentialWaitForEvent,
    specialCharacters,
    happyPath,
  ],
});
